config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  resources :questions, only: [:index, :new, :create, :show] do
   resources :answers, only: :create
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    Answer.create(answer_params)
    redirect_to root_path
  end

  private
    def answer_params 
    params.require(:answer).permit(:answercontent, :answername).merge( question_id: params[:question_id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
   @questions = Question.all
  end

  def new
   @question = Question.new
  end

  def create
   Question.create(question_params)
   redirect_to action: :index
  end

  def show
   @question = Question.find(params[:id])
   @answer = Answer.new
   @answers = @question.answers
  end

  private 
  def question_params
   params.require(:question).permit(:title, :content, :name)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <header>
    <div class = "header-main">
     <div class = "header-title">
     <%= link_to 'TechChat', root_path %>

     </div>
     <div class="header-button"> 
       <%= link_to '質問する', new_question_path %>
      </div>
    </div>
   </header>
   <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
  <div class ="index-main">
      <div class="comment-entire">
         <% @questions.each do |question| %>
            <div class="post-content">
               <div class="comment">
                 <div class="comment-number">0</div>
                 <div class="comment-title">comments</div>
               </div>
               <div class="question">
                  <div class="question-top">
                     <div class="title-name">
                       <%= link_to question.title, question_path(question.id) %>
                     </div>
                     <div class="questioner"><%= question.name %></div>
                  </div>
                  <div class="question-bottom">
                     <div><%= question.content %></div>
                  </div>
               </div>
            </div>   
         <% end %>
      </div>
  </div>

app/views/questions/new.html.erb
<div class="full" style="height: calc(100vh - 65px); background-color: #F2F2F3;">
  <div class="ask-entire">
        <%= form_with model: @question, local: true do |form| %>
           <div class="form-coloring">
              <div class="head-part"></div>
              <div class="main-part">
                <div class="main-detail">
                    <div class="main-title">
                      <%= form.text_field :title, placeholder: "タイトル" %>
                    </div>
                    <div class="main-question">
                      <%= form.text_area :content, placeholder: "質問内容" %>
                    </div>
                    <div class="main-name">
                      <%= form.text_field :name, placeholder: "名前" %>
                    </div>
                    <div class="main-button">
                      <%= form.submit 'POST' %>
                    </div>
                  </div>
              </div>
          </div>
        <% end %>
   </div>
</div>

app/views/questions/show.html.erb
<div class="main">
  <div class="show-contents">

      <div class="title-name-show">
         タイトル:<%= @question.title %>
      </div>
      </div>
      <div class="question-bottom-show">
         質問内容:<%= @question.content %>
      </div>
      <div class="question-top">
      <div class="questioner-show">
         投稿者名:<%= @question.name %>
      </div>
      </div><br>

      <%= form_with(model: [@question, @answer], local: true) do |form| %>
      <%= form.text_area :text, placeholder: "回答する", rows: "2" %><br>
      <%= form.text_field :string, placeholder: "ユーザー名" %><br>
      <%= form.submit "POST" %>   
      <% end %>


      <% @answers.each do |answer| %><br>
      回答:<%= answer.answercontent %><br>
      投稿者:<%= answer.answername %><br>
      <% end %>
   </div>
</div>